apiVersion: apps/v1
kind: Deployment
metadata:
  name: commande-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commande-service
  template:
    metadata:
      labels:
        app: commande-service
    spec:
      containers:
        - name: commande-service
          image: dianaouldchikh/commande-service:1.0
          ports:
            - containerPort: 8082

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker

            - name: CONFIG_SERVER_URL
              value: http://config-service:8888

            - name: EUREKA_SERVER_URL
              value: http://discovery-service:8761/eureka

            # Configuration PostgreSQL
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/service2db

            - name: SPRING_DATASOURCE_USERNAME
              value: service1user

            - name: SPRING_DATASOURCE_PASSWORD
              value: service1pass

            - name: SPRING_DATASOURCE_DRIVER
              value: org.postgresql.Driver

            - name: SPRING_JPA_PLATFORM
              value: org.hibernate.dialect.PostgreSQLDialect
